#!/bin/bash

dnf update -y
dnf install -y glibc.i686 alsa-lib at-spi2-atk at-spi2-core atk avahi-libs cairo cairo-gobject cups-libs dbus-libs expat fribidi gdk-pixbuf2 glib2 glibc glibc-devel gnutls graphite2 gtk3 gzip harfbuzz json-glib keyutils-libs krb5-libs libXcomposite libXcursor libXdamage libXfixes libXi libXinerama libXrandr libXrender libXxf86vm libblkid libcap libcom_err libdatrie libdrm libepoxy libffi libgcrypt libglvnd libglvnd-egl libgpg-error libicu libidn2 libjpeg-turbo libmount libnsl libselinux libstemmer libtasn1 libthai libtracker-sparql libunistring libuuid libwayland-client libwayland-cursor libwayland-egl libwayland-server libxcb libxcrypt-compat libxkbcommon libxml2 mesa-libgbm nettle nspr nss nss-util openssl-libs p11-kit pango pcre2 pixman systemd-libs tar which xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi
echo "--->Packages Required for the Installer to Run<---"
dnf install -y bzip2-libs cyrus-sasl-lib fontconfig freetype glib2 glibc graphite2 harfbuzz keyutils-libs krb5-libs libICE libSM libX11 libX11-xcb libXau libXext libbrotli libcom_err libcurl libevent libidn2 libnghttp2 libpng libpsl libselinux libssh libunistring libuuid libxcb libxcrypt libxkbcommon libxkbcommon-x11 libxml2 openldap openssl-libs pcre pcre2 xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs zlib
echo "--->ACIS Geometry Interface<---"
dnf install -y abseil-cpp fontconfig grpc grpc-cpp jbigkit-libs libICE libSM libX11 libXau libXext libXft libXmu libXp libXt libatomic libcurl-devel libibverbs libnl3 libpciaccess libpng libquadmath librdmacm libtiff libuuid-devel libwebp libzstd lz4-libs motif pcre re2 ucx xz-libs
echo "--->Additive<---"
dnf install -y cyrus-sasl-lib elfutils-libelf enchant2 fontconfig gstreamer1 gstreamer1-plugins-base harfbuzz-icu hyphen jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libglvnd-glx libglvnd-opengl libibverbs libicu50 libnghttp2 libnl3 libnotify libpciaccess libpng12 libpsl librdmacm libseccomp libsecret libsoup libssh libtiff libwebp libwpe libxcrypt libxshmfence libxslt libzstd lz4-libs ncurses-libs nss-softokn numactl-libs openjpeg2 openldap orc pcre perl-devel ucx webkit2gtk3 webkit2gtk3-jsc woff2 wpebackend-fdo xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm
echo "--->Ansys Dynamic Reporting<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap openldap-compat perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Customization Files for User Programmable Features<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Aqwa<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Autodyn<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Catia - Version 5 Geometry Interface<---"
dnf install -y abseil-cpp fontconfig grpc grpc-cpp jbigkit-libs libICE libSM libX11 libXau libXext libXft libXmu libXp libXt libatomic libcurl-devel libibverbs libnl3 libpciaccess libpng libquadmath librdmacm libtiff libuuid-devel libwebp libzstd lz4-libs motif pcre re2 ucx xz-libs
echo "--->CFD-Post only<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn nss-softokn-freebl openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->CFX includes CFD-Post<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence lz4-libs nss-softokn nss-softokn-freebl openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Chemkin<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->EnSight<---"
dnf install -y audit-libs bzip2-libs cyrus-sasl-lib elfutils-libelf freetype gtk2 jbigkit-libs libX11 libXau libXdmcp libXext libXft libXtst libatomic libbrotli libcap-ng libcurl libeconf libfontenc libglvnd-glx libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence ncurses-libs nss-softokn nss-softokn-freebl numactl-libs openldap openldap-compat pam pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs zlib
echo "--->FENSAP-ICE<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn nss-softokn-freebl openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Fluent includes CFD-Post<---"
dnf install -y audit-libs bzip2-libs cyrus-sasl-lib elfutils-libelf freetype gtk2 jbigkit-libs libX11 libXau libXdmcp libXext libXft libXtst libatomic libbrotli libcap-ng libcurl libeconf libfontenc libglvnd-glx libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence ncurses-libs nss-softokn nss-softokn-freebl numactl-libs openldap openldap-compat pam pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs zlib
echo "--->Forte includes EnSight<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap openldap-compat perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->ICEM CFD<---"
dnf install -y libICE.i686 libSM.i686 libX11.i686 libXau.i686 libXt.i686 libgcc.i686 libstdc++.i686 libuuid.i686 libxcb.i686 cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Icepak includes CFD-Post<---"
dnf install -y libX11.i686 libXau.i686 libXext.i686 libglvnd-glx.i686 libxcb.i686 audit-libs bzip2-libs cyrus-sasl-lib elfutils-libelf fontconfig freetype jbigkit-libs libX11 libXau libXdmcp libXext libXft libXtst libatomic libbrotli libcap-ng libcurl libeconf libfontenc libglvnd-glx libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence ncurses-libs nss-softokn nss-softokn-freebl numactl-libs openldap openldap-compat pam pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs zlib
echo "--->Ansys - Inc - License Manager<---"
dnf install -y bzip2-libs fontconfig freetype glib2 glibc graphite2 harfbuzz libICE libSM libX11 libXau libXext libXrender libbrotli libgcc libpng libstdc++ libuuid libxcb libxml2 pcre xz-libs zlib
echo "--->LS-DYNA<---"
dnf install -y bzip2-libs cyrus-sasl-lib fontconfig libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libnotify libogg libpciaccess libpng12 libpsl librdmacm libsecret libssh libtheora libvorbis libxcrypt libxshmfence libzstd lz4-libs nss-softokn openjpeg2 openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Mechanical Products<---"
dnf install -y cyrus-sasl-lib elfutils-libelf enchant2 fontconfig gstreamer1 gstreamer1-plugins-base harfbuzz-icu hyphen jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libglvnd-glx libglvnd-opengl libibverbs libicu50 libnghttp2 libnl3 libnotify libpciaccess libpng12 libpsl librdmacm libseccomp libsecret libsoup libssh libtiff libwebp libwpe libxcrypt libxshmfence libxslt libzstd lz4-libs ncurses-libs nss-softokn nss-softokn-freebl numactl-libs openjpeg2 openldap orc pcre perl-devel ucx webkit2gtk3 webkit2gtk3-jsc woff2 wpebackend-fdo xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xterm
echo "--->Model Fuel Library Encrypted<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Motion<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->NX Geometry Interface<---"
dnf install -y abseil-cpp fontconfig grpc grpc-cpp jbigkit-libs libICE libSM libX11 libXau libXext libXft libXmu libXp libXt libatomic libcurl-devel libibverbs libnl3 libpciaccess libpng libquadmath librdmacm libtiff libuuid-devel libwebp libzstd lz4-libs motif pcre re2 ucx xz-libs
echo "--->optiSLang<---"
dnf install -y bzip2-libs flac-libs fontconfig freetype gsm jbigkit-libs libICE libSM libX11 libX11-xcb libXau libXext libXtst libasyncns libbrotli libglvnd-glx libglvnd-opengl libogg libpng libreoffice-ure libsndfile libtiff libvorbis libwebp libxkbcommon-x11 libzstd lz4-libs mesa-libGLU ocl-icd opus pcre pulseaudio-libs pulseaudio-libs-glib2 xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Parasolid Geometry Interface<---"
dnf install -y abseil-cpp fontconfig grpc grpc-cpp jbigkit-libs libICE libSM libX11 libXau libXext libXft libXmu libXp libXt libatomic libcurl-devel libibverbs libnl3 libpciaccess libpng libquadmath librdmacm libtiff libuuid-devel libwebp libzstd lz4-libs motif pcre re2 ucx xz-libs
echo "--->Polyflow includes CFD-Post<---"
dnf install -y audit-libs bzip2-libs cyrus-sasl-lib elfutils-libelf freetype gtk2 jbigkit-libs libX11 libXau libXdmcp libXext libXft libXtst libatomic libbrotli libcap-ng libcurl libeconf libfontenc libglvnd-glx libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence ncurses-libs nss-softokn nss-softokn-freebl numactl-libs openldap openldap-compat pam pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs zlib
echo "--->Reaction Workbench<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Remote Solve Manager Standalone Services<---"
dnf install -y cyrus-sasl-lib fontconfig jbigkit-libs libICE libSM libX11 libX11-xcb libXau libXext libXft libXmu libXp libXt libXtst libatomic libbrotli libcurl libcurl-devel libgfortran libibverbs libnghttp2 libnl3 libpciaccess libpsl libquadmath librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs motif nss-softokn openldap pcre ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Sherlock<---"
dnf install -y cyrus-sasl-lib elfutils-libelf fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs ncurses-libs nss-softokn numactl-libs openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
echo "--->Speos HPC<---"
dnf install -y bzip2-libs fontconfig freetype jbigkit-libs libICE libSM libX11 libXau libXext libXft libXmu libXp libXt libatomic libbrotli libcurl-devel libgfortran libglvnd-glx libgomp libibverbs libnl3 libpciaccess libpng libquadmath librdmacm libtiff libwebp libzstd lz4-libs mesa-libGLU motif pcre ucx xz-libs
echo "--->TurboGrid<---"
dnf install -y libgcc.i686 cyrus-sasl-lib fontconfig jbigkit-libs libXft libXtst libatomic libbrotli libcurl libcurl-devel libibverbs libicu50 libnghttp2 libnl3 libpciaccess libpng12 libpsl librdmacm libssh libtiff libwebp libxcrypt libxshmfence libzstd lz4-libs nss-softokn nss-softokn-freebl openldap pcre perl-devel ucx xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xz-libs
