---
- name: Copy dependencies installation script
  ansible.builtin.copy:
    src: files/install-dependencies-{{ ANSYS_VERSION }}-rl-9.sh
    dest: /tmp/install-dependencies-{{ ANSYS_VERSION }}-rl-9.sh
    mode: "755"

- name: Run dependencies installation script
  ansible.builtin.shell:
    chdir: 
    cmd: |
      /tmp/install-dependencies-{{ ANSYS_VERSION }}-rl-9.sh
...
