---
- name: Download Lmod package
  ansible.builtin.get_url:
    url: https://codeload.github.com/TACC/Lmod/tar.gz/refs/tags/8.7.37
    dest: /tmp/Lmod-8.7.37.tar.gz

- name: Unpack Lmod
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/Lmod-8.7.37.tar.gz
    dest: /tmp

- name: Install dependencies (RedHat)
  ansible.builtin.dnf:
    enablerepo: devel
    name:
      - tcl
      - tcl-devel
      - make
      - bzip2
      - bc
      - lua-devel
  when: ansible_facts['os_family'] == "RedHat"

- name: Install dependencies (Debian)
  ansible.builtin.apt:
    name:
      - lua5.3
      - lua-bit32:amd64
      - lua-posix:amd64
      - lua-posix-dev
      - liblua5.3-0:amd64
      - liblua5.3-dev:amd64
      - tcl
      - tcl-dev
      - tcl8.6
      - tcl8.6-dev:amd64
      - libtcl8.6:amd64
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Lmod
  ansible.builtin.shell:
    chdir: /tmp/Lmod-8.7.37
    cmd: |
      ./configure --prefix=/opt/apps
      make install
      ln -sf /opt/apps/lmod/lmod/init/profile /etc/profile.d/z00_lmod.sh
  register: res
  failed_when: '"Error" in res'

- name: Create /etc/lmod
  ansible.builtin.file:
    path: /etc/lmod
    state: directory

- name: Copy modulespath config file
  ansible.builtin.copy:
    src: files/.modulespath
    dest: /etc/lmod/.modulespath
...
