---
- name: Download Lua tar file 
  ansible.builtin.get_url:
    url: https://sourceforge.net/projects/lmod/files/lua-5.1.4.8.tar.gz/download
    dest: /tmp/lua-5.1.4.8.tar.bz2
    
- name: Install tar package (RedHat)
  ansible.builtin.dnf:
    name: tar
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install tar package (Debian)
  ansible.builtin.apt:
    name: tar
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Unpack Lua tar file
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/lua-5.1.4.8.tar.bz2
    dest: /tmp

- name: Install rsync (RedHat)
  ansible.builtin.dnf:
    name: 
      - rsync
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install rsync (Debian)
  ansible.builtin.apt:
    name: 
      - rsync
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Development Tools (RedHat)
  ansible.builtin.dnf:
    name: '@Development tools'
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Development Tools (Debian)
  ansible.builtin.apt:
    name: build-essential
    state: present
  when: ansible_facts['os_family'] == "Debian"


- name: Configure and build Lua
  ansible.builtin.shell:
    chdir: /tmp/lua-5.1.4.8
    cmd: |
      ./configure --with-static=yes --prefix=/opt/lua && make && make install
...
