---
- name: Configure IPA server
  hosts: ipaservers
  become: true
  gather_facts: true

  roles:
    - role: ipa
      vars:
        IPA_CONFIGURE_SERVER: TRUE

- name: Configure IPA clients
  hosts: ipaclients
  become: true
  gather_facts: true

  roles:
    - role: ipa
      vars:
        IPA_CONFIGURE_CLIENT: TRUE
...
