---
- name: Add ssh login banner
  block:
    - name: Copy banner
      ansible.builtin.copy:
        src: files/restricted-ssh-banner.txt
        dest: /etc/ssh/restricted-ssh-banner.txt

    - name: Make sure sshd config file points to banner
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Banner'
        line: Banner /etc/ssh/restricted-ssh-banner.txt

    - name: Restart sshd service
      ansible.builtin.systemd_service:
        name: sshd 
        state: restarted

...